language: node_js
services: rabbitmq
os:
  - linux
addons:
  apt:
    packages:
      - rabbitmq-server
node_js:
  - 'stable'
  - 'lts/*'

script:
  - npm run tslint
  - npm test

cache:
  directories:
    - node_modules
