rabbitmq:
  image: rabbitmq:3-management-alpine
  ports:
    - '5672:5672'
    - '15672:15672' # Rabbitmq admin
  volumes:
    - rabbitmq:/var/lib/rabbitmq
  restart: always
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
